version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-multistream-{{ checksum "project.clj" }}
            - clj-multistream-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: clj-multistream-{{ checksum "project.clj" }}
      - run: lein do check, test
      - run: lein with-profile +coverage cloverage --codecov
      - store_artifacts:
          path: target/coverage
          destination: coverage
      - run:
          name: Publish Coverage
          command: "(curl -s https://codecov.io/bash > codecov) && bash codecov -f target/coverage/codecov.json"
